name: Generate ASCII ArtWork
on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Welcome
          run: echo "Hello World from GitHub Actions"
        - name: pwd
          run: pwd
        - name: Checkout
          uses: actions/checkout@v6.0.2

        - name: Install Cowsay Program
          run: sudo apt-get install cowsay -y
            
        - name: Generate ASCII Artwork
          run: cowsay -f dragon "Run for cover, Hello! I'm a Dragon... grrrr!" >> dragon.txt
        
        - name: Read Dragon File
          run: cat dragon.txt

        - name: List Repo Files
          run: ls -ltra
