name: Generate ASCII ArtWork executing sh
on: push

jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
        - name: Welcome
          run: echo "Hello World! from GitHub Actions"

        - name: Checkout
          uses: actions/checkout@v6.0.2

        - name: pwd and ls
          run: |
            pwd
            ls -lart

        - name: Executing Shell Script
          run: |
            chmod +x ascii.script.sh
            ./ascii.script.sh
            sleep 10

    ascii_job2:
        runs-on: ubuntu-latest
        steps:
        - name: Welcome
          run: echo "Hello World! from GitHub Actions"

        - name: Checkout
          uses: actions/checkout@v6.0.2

        - name: pwd and ls
          run: |
            pwd
            ls -lart

        - name: Executing Shell Script
          run: |
            chmod +x ascii.script2.sh
            ./ascii.script2.sh
            sleep 10

 


